kind: CronJob
apiVersion: batch/v1beta1
metadata:
  name: kiali-maistra-labels
  namespace: default
  selfLink: /apis/batch/v1beta1/namespaces/default/cronjobs/example
  uid: 5b41971b-53b0-4dcd-a664-898cf98cde9f
  resourceVersion: '688991'
  creationTimestamp: '2020-07-22T23:54:59Z'
spec:
  schedule: '*/1 * * * *'
  concurrencyPolicy: Allow
  suspend: false
  jobTemplate:
    metadata:
      creationTimestamp: null
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          volumes:
            - name: configmap
              configMap:
                name: script
                defaultMode: 511
          containers:
            - name: kiali-maistra-labels
              image: 'registry.redhat.io/openshift4/ose-cli:v4.3'
              args:
                - /bin/sh
                - '-c'
                - /configmap/run.sh
              resources: {}
              volumeMounts:
                - name: configmap
                  mountPath: /configmap
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
              imagePullPolicy: IfNotPresent
          restartPolicy: OnFailure
          terminationGracePeriodSeconds: 30
          dnsPolicy: ClusterFirst
          securityContext: {}
          schedulerName: default-scheduler
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
